[package]
name = "toy-lang"
version = "0.1.0"
authors = ["Lawrence Horton <lawrencephorton@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
